var posters = { "posters" : [
  {"_id":{"$oid":"553fb925467be23b30a482ad"},"artist":"Andrzej Pagowski","description":"8½ (Italian title: Otto e mezzo) is a 1963 Italian comedy-drama film directed by Federico Fellini. Co-scripted by Fellini, Tullio Pinelli, Ennio Flaiano, and Brunello Rondi, it stars Marcello Mastroianni as Guido Anselmi, a famous Italian film director. Shot in black-and-white by cinematographer Gianni di Venanzo, the film features a soundtrack by Nino Rota with costume and set designs by Piero Gherardi.","director":"Federico Fellini","size":[67,95],"title":{"EN":"8½","GER":"Achteinhalb","IT":"Otto e mezzo","PL":"8½"},"url":"8","www":"http://en.wikipedia.org/wiki/8%C2%BD","year":{"movie":1963,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48280"},"artist":"Wieslaw Walkuski","description":"And the Ship Sails On (Italian: E la nave va) is a 1983 Italian film by Federico Fellini. It depicts the events on board a luxury liner filled with the friends of a deceased opera singer who have gathered to mourn her. The film was selected as the Italian entry for the Best Foreign Language Film at the 56th Academy Awards, but was not accepted as a nominee.","director":"Federico Fellini","size":[84,59],"title":{"EN":"And the Ship Sails On","GER":"Fellinis Schiff der Träume","IT":"E la nave va","PL":"A statek płynie"},"url":"a_statek_plynie","www":"http://en.wikipedia.org/wiki/And_the_Ship_Sails_On","year":{"movie":1983,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482a1"},"artist":"Romuald Socha","description":"Alice or the Last Escapade (French: ''Alice ou la dernière fugue'') is a 1977 film written and directed by Claude Chabrol. The film is very loosely inspired by Alice's Adventures in Wonderland by Lewis Carroll, including the protagonist's name being Alice Carroll (a combination of the Alice character and the author's pseudonymous surname).","director":"Claude Chabrol","size":[67,95],"title":{"EN":"Alice or the Last Escapade","FR":"Alice ou la dernière fugue","GER":"","PL":"Alicja ucieka po raz ostatni"},"url":"alicja_ucieka_po_raz_ostatni","www":"http://en.wikipedia.org/wiki/Alice_or_the_Last_Escapade","year":{"movie":1977,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48267"},"artist":"-","description":"Ten film nie ma jeszcze zarysu fabuły.","director":"Václav Matějka","size":[84,59],"title":{"PL":"Anielska Diablica"},"url":"anielska_diablica","www":"http://www.filmweb.pl/film/Anielska+diablica-1983-188894","year":{"movie":1983,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48281"},"artist":"Andrzej Pagowski","description":"Le bal is a 1983 Italian-Franco-Algerian film without dialogue directed by Ettore Scola that represents a fifty-year story of French society by way of a ballroom in France.","director":"Ettore Scola","size":[67,95],"title":{"EN":"Le Bal","FR":"Le Bal","GER":"Le Bal – Der Tanzpalast","PL":"Bal"},"url":"bal","www":"http://en.wikipedia.org/wiki/Le_Bal_(film)","year":{"movie":1983,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48268"},"artist":"Andrzej Pagowski","description":"No End is a 1985 film directed by Krzysztof Kieślowski and starring Grażyna Szapołowska, Maria Pakulnis, and Aleksander Bardini. The film is about the state of Martial law in Poland after the banning of the trade union Solidarity in 1981. Kieślowski worked with several regular collaborators for the first time on No End.","director":"Krzysztof Kieślowski","size":[67,95],"title":{"EN":"No End","PL":"Bez końca"},"url":"bez_konca","www":"http://en.wikipedia.org/wiki/No_End_%28film%29","year":{"movie":1985,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4829a"},"artist":"Andrzej Pagowski","description":"Close Encounters of the Third Kind is a 1977 science fiction film, written and directed by Steven Spielberg and featuring Richard Dreyfuss, François Truffaut, Melinda Dillon, Teri Garr, Bob Balaban, and Cary Guffey. It tells the story of Roy Neary, an everyday blue collar worker in Indiana, whose life changes after an encounter with an unidentified flying object (UFO).","director":"Steven Spielberg","size":[67,95],"title":{"EN":"Close Encounters of the Third Kind","GER":"-","PL":"Bliskie spotkania trzeciego stopnia"},"url":"bliskie_spotkania_trzeciego_stopnia","www":"http://en.wikipedia.org/wiki/Close_Encounters_of_the_Third_Kind","year":{"movie":1977,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48269"},"artist":"-","description":"Trzydziestoletnia Kinga właśnie rozwiodła się z mężem i samotnie wychowuje córkę. Nowy romans nie układa się po jej myśli, coraz bardziej nudzi ją też praca. Sfrustrowana kobieta bierze urlop, aby spełnić swe marzenie i napisać książkę.","director":"Hanka Wlodarczyk","size":[57,83],"title":{"PL":"Bluszcz"},"url":"bluszcz","www":"http://pl.wikipedia.org/wiki/Bluszcz_%28film%29","year":{"movie":1982,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4826c"},"artist":"Jakub Erol","description":"The Belly of an Architect is a 1987 film drama written and directed by Peter Greenaway, featuring original music by Glenn Branca and Wim Mertens. The movie stars Brian Dennehy and Chloe Webb and contains numerous references to the work of the 18th century French architect Étienne-Louis Boullée. It was nominated for the Palme d'Or (Golden Palm) award at the 1987 Cannes Film Festival.","director":"Peter Greenaway","size":[67,95],"title":{"EN":"The Belly of an Architect","GER":"Der Bauch des Architekten","PL":"Brzuch Architekta"},"url":"brzuch_architekta","www":"http://en.wikipedia.org/wiki/The_Belly_of_an_Architect","year":{"movie":1987,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48299"},"artist":"Jakub Erol","description":"Carmen (1984) is a film directed by Francesco Rosi. It is a film version of Bizet's opera Carmen.[1] Julia Migenes stars in the title role, Plácido Domingo as Don José, Ruggero Raimondi as Escamillo, and Faith Esham as Micaela. Lorin Maazel conducts the Orchestre National de France.","director":"Francesco Rosi","size":[67,95],"title":{"EN":"Carmen","GER":"Carmen","PL":"Carmen"},"url":"carmen","www":"http://en.wikipedia.org/wiki/Carmen_%281984_film%29","year":{"movie":1984,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48260"},"artist":"Eugeniusz Skorwider","description":"Malady of Love (French: Maladie d'amour) is a 1987 French drama romance film, directed by Jacques Deray.","director":"Jacques Deray","size":[67,95],"title":{"EN":"Malady of Love ","FR":"Maladie d'amour","GER":"Krank vor Liebe","PL":"Chora z miłości"},"url":"chora_z_milosci","www":"http://en.wikipedia.org/wiki/Malady_of_Love","year":{"movie":1987,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48282"},"artist":"Grzegorz Marszalek","description":"Christ Stopped at Eboli (Italian: Cristo si è fermato a Eboli) is a 1979 film adaptation of the book of the same name by Carlo Levi. It was directed by Francesco Rosi and stars Gian Maria Volonté as Carlo Levi, with Paolo Bonacelli, Alain Cuny, Léa Massari, and Irene Papas.","director":"Francesco Rosi","size":[67,95],"title":{"EN":"Christ Stopped at Eboli","GER":"Christus kam nur bis Eboli","IT":"Cristo si è fermato a Eboli","PL":"Chrystus zatrzymał się w Eboli"},"url":"chrystus_zatrzymal_sie_w_eboli","www":"http://en.wikipedia.org/wiki/Christ_Stopped_at_Eboli_(film)","year":{"movie":1979,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4829b"},"artist":"Marian Nowinski","description":"Ciuleandra is a 1985 Romanian drama film directed by Sergiu Nicolaescu. The film was selected as the Romanian entry for the Best Foreign Language Film at the 58th Academy Awards, but was not accepted as a nominee.","director":"Sergiu Nicolaescu","size":[67,95],"title":{"EN":"Ciuleandra","GER":"-","PL":"Ciuleandra"},"url":"ciuleandra","www":"http://en.wikipedia.org/wiki/Ciuleandra","year":{"movie":1985,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4829c"},"artist":"Anna Kozlowska","description":"Coma is a 1978 suspense film based on the 1977 novel of the same name by Robin Cook. The film rights were acquired by director Michael Crichton, and the movie was produced by Martin Erlichmann for Metro-Goldwyn-Mayer. The cast includes Geneviève Bujold, Michael Douglas, Elizabeth Ashley, Richard Widmark, and Rip Torn. Among the actors in smaller roles are Tom Selleck, Lois Chiles, and Ed Harris.","director":"Michael Crichton","size":[67,95],"title":{"EN":"Coma","GER":"Coma","PL":"Coma"},"url":"coma","www":"http://en.wikipedia.org/wiki/Coma_(1978_film)","year":{"movie":1978,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48276"},"artist":"A. Laudis","description":"Miroslav Opatovský (Milan Karpisek) jest damskim krawcem, pracującym w dużym salonie mody. Jest żonaty, ceniony w pracy, przez otoczenie uważany za porządnego człowieka.","director":"Otakar Fuka","size":[47.5,68.5],"title":{"EN":"-","GER":"-","PL":"Czarna pończocha"},"url":"czarna_ponczocha","www":"http://www.filmweb.pl/film/Czarna+po%C5%84czocha-1987-178037","year":{"movie":1987,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482c7"},"artist":"Lech Majewski","description":"The Marathon Family (Serbo-Croatian: Maratonci trče počasni krug, lit. The Marathoners Run the Lap of Honour, or often simply Maratonci) is a 1982 comedy film written by Dušan Kovačević and directed by Serbian director Slobodan Šijan. It has a cult film status in Serbia as well as other countries from the former Yugoslavia region, and is regarded as one of the classics of Yugoslav Serbian cinematography.","director":"Slobodan Šijan","size":[67,95],"title":{"EN":"The Marathon Family","GER":"-","PL":"Długowieczna rodzinka"},"url":"dlugowieczna_rodzinka","www":"http://en.wikipedia.org/wiki/The_Marathon_Family","year":{"movie":1982,"poster":1983}},
  {"_id":{"$oid":"553fb925467be23b30a4829d"},"artist":"Maciej Kalkus","description":"The Medusa Touch is a 1978 British supernatural thriller film directed by Jack Gold. It starred Richard Burton, Lino Ventura, Lee Remick and Harry Andrews, with cameos by Alan Badel, Derek Jacobi, Gordon Jackson, Jeremy Brett and Michael Hordern. The screenplay was by John Briley, based on the novel The Medusa Touch by Peter Van Greenaway.","director":"Jack Gold","size":[67,95],"title":{"EN":"The Medusa Touch","GER":"Der Schrecken der Medusa","PL":"Dotknięcie Meduzy"},"url":"dotkniencie_meduzy","www":"http://en.wikipedia.org/wiki/The_Medusa_Touch_(film)","year":{"movie":1978,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4825c"},"artist":"Wieslaw Walkuski","description":"Rosemary's Baby is a 1968 American psychological horror film written and directed by Roman Polanski, based on the bestselling 1967 novel Rosemary's Baby by Ira Levin.","director":"Roman Polanski","size":[67,95],"title":{"EN":"Rosemary's Baby","GER":"Rosemaries Baby","PL":"Dziecko Rosemary"},"url":"dziecko_rosemary","www":"https://en.wikipedia.org/wiki/Rosemary%27s_Baby_%28film%29","year":{"movie":1968,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48283"},"artist":"Jacek Neugebauer","description":"Lipstick is an American 1976 rape and revenge drama film directed by Lamont Johnson and starring Margaux and Mariel Hemingway.","director":"Lamont Johnson","size":[84,59],"title":{"EN":"Lipstick","GER":"Eine Frau sieht rot","PL":"Dziewczyna z reklamy"},"url":"dziewczyna_z_reklamy","www":"http://en.wikipedia.org/wiki/Lipstick_(film)","year":{"movie":1976,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482c8"},"artist":"Wieslaw Walkuski","description":"Fanny and Alexander (Swedish: Fanny och Alexander) is a 1982 Swedish drama film written and directed by Ingmar Bergman. The plot focuses on two siblings and their large family in Uppsala, Sweden in the 1900s. It was originally conceived as a four-part TV movie and cut in that version, spanning 312 minutes; a 188-minute cut version was created later for cinematic release, although this version was in fact the one to be released first. The TV version has since been released as a one-part film, and both versions have been shown in theaters throughout the world. The 312-minute cut of the film ranks it among one of the longest cinematic films in history.","director":"Ingmar Bergmann","size":[67,95],"title":{"EN":"Fanny and Alexander","GER":"Fanny und Alexander","PL":"Fanny i Alexander","SE":"Fanny och Alexander"},"url":"fanny_i_aleksander","www":"http://en.wikipedia.org/wiki/Fanny_and_Alexander","year":{"movie":1982,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48298"},"artist":"Jakub Erol","description":"Fedora is a 1978 West German-French drama film directed by Billy Wilder. The screenplay by Wilder and I.A.L. Diamond is based on a novella by Tom Tryon included in his collection Crowned Heads, published in 1976. The film stars William Holden and Marthe Keller.","director":"Billy Wilder","size":[67,95],"title":{"EN":"Fedora","FR":"Fedora","GER":"Fedora","PL":"Fedora"},"url":"fedora","www":"http://en.wikipedia.org/wiki/Fedora_(film)","year":{"movie":1978,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482af"},"artist":"Eugeniusz Skorwider","description":"Gabriela is a 1983 Brazilian romance film directed by Bruno Barreto. It was shot in the cities of Paraty, in the state of Rio de Janeiro, and in Garopaba, Santa Catarina.","director":"Bruno Barreto","size":[95,67],"title":{"BRA":"Gabriela","EN":"Gabriela","GER":"Gabriela","PL":"Gabriela"},"url":"gabriela","www":"http://en.wikipedia.org/wiki/Gabriela_(1983_film)","year":{"movie":1983,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4829e"},"artist":"-","description":"Ten film nie ma jeszcze zarysu fabuły","director":"Romuald Socha","size":[67,95],"title":{"EN":"-","GER":"-","PL":"Gon mnie az cie zlapie"},"url":"gon_mnie_az_cie_zlapie","www":"#","year":{"movie":1978,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4825f"},"artist":"Jakub Erol","description":"The Name of the Rose is a 1986 film directed by Jean-Jacques Annaud, based on the book of the same name by Umberto Eco. Sean Connery is the Franciscan friar William of Baskerville and Christian Slater is his apprentice Adso of Melk, who are called upon to solve a deadly mystery in a medieval abbey.","director":"Jean-Jacques Annaud","size":[67,95],"title":{"EN":"The Name of the Rose","GER":"Im Namen der Rose","IT":"Il nome della rosa","PL":"Imię róży"},"url":"imie_rozy","www":"http://en.wikipedia.org/wiki/The_Name_of_the_Rose_%28film%29","year":{"movie":1986,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4829f"},"artist":"Andrzej Pagowski","description":"Empire of Passion (愛の亡霊 Ai no Bōrei?) is a 1978 French-Japanese film directed by Nagisa Ōshima.","director":"Nagisa Oshima","size":[67,95],"title":{"EN":"Empire of Passion","GER":"Im Reich der Leidenschaft","PL":"Imperium namiętności"},"url":"imperium_namietnosci","www":"http://en.wikipedia.org/wiki/Empire_of_Passion","year":{"movie":1978,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482b0"},"artist":"Andrzej Pagowski","description":"Empire of the Sun is a 1987 American coming of age war film based on J. G. Ballard's semi-autobiographical novel of the same name. Steven Spielberg directed the film, which stars Christian Bale, John Malkovich, Miranda Richardson, and Nigel Havers. The film tells the story of Jamie 'Jim' Graham, a young boy who goes from living in a wealthy British family in Shanghai, to becoming a prisoner of war in a Japanese internment camp, during World War II.","director":"Steven Spielberg","size":[84,59],"title":{"EN":"Empire of the Sun","GER":"Das Reich der Sonne","PL":"Imperium Słońca"},"url":"imperium_slonca","www":"http://en.wikipedia.org/wiki/Empire_of_the_Sun_(film)","year":{"movie":1987,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48297"},"artist":"Jan Mlodozeniec","description":"The Serpent's Egg is a 1977 American-West German drama film directed by Ingmar Bergman and starring David Carradine and Liv Ullmann. The story is set in 1920s Berlin and features English and German dialogue. This was Bergman's one and only Hollywood film. The title is taken from a line spoken by Brutus in Shakespeare's Julius Caesar: And therefore think him as a serpent's egg/Which hatch'd, would, as his kind grow mischievous;/And kill him in the shell.","director":"Ingmar Bergmann","size":[67,95],"title":{"EN":"The Serpent's Egg","GER":"Das Schlangenei","PL":"Jajo węża"},"url":"jajo_weza","www":"http://en.wikipedia.org/wiki/The_Serpent%27s_Egg_(film)","year":{"movie":1977,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48261"},"artist":"Witold Janowski","description":"How to be Loved (Polish: Jak być kochaną), a Polish film released in 1963, directed by Wojciech Has. The film, based on a novel of the same name by Kazimierz Brandys, examines the emotional casualties of war, which is perhaps the central theme of the Polish Film School. On a deeper level, the film manages to construct a personal tragedy that results from a struggle of egoism and cowardice versus devotion and courage.","director":"Wojciech Has","size":[58,83],"title":{"EN":"How to be Loved","PL":"Jak być kochaną"},"url":"jak_byc_kochana","www":"http://en.wikipedia.org/wiki/How_to_Be_Loved","year":{"movie":1963,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482b1"},"artist":"Maria Ekier","description":"How Poets Are Enjoying Their Lives (Czech: Jak básníkům chutná život) is a Czech comedy film directed by Dusan Klein. It was released in 1988.","director":"Dušan Klein","size":[67,95],"title":{"CZ":"Jak básníkům chutná život","EN":"How Poets Are Enjoying Their Lives","GER":"-","PL":"Jak poeci tracą złudzenia"},"url":"jak_poeci_traca_zludzenia","www":"http://en.wikipedia.org/wiki/How_Poets_Are_Enjoying_Their_Lives","year":{"movie":1987,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482b2"},"artist":"Mieczyslaw Wasilewski","description":"A Woman Under the Influence is a 1974 American drama film written and directed by John Cassavetes. It focuses on a woman whose unusual behavior leads her husband to commit her for psychiatric treatment and the effect this has on their family. It received two Academy Award nominations for Best Actress and Best Director. In 1990, A Woman Under the Influence was selected for preservation in the United States National Film Registry as being 'culturally, historically, or aesthetically significant', one of the first fifty films to be so honored.","director":"John Cassavetes","size":[59,84],"title":{"EN":"A Woman Under the Influence","GER":"http://de.wikipedia.org/wiki/Eine_Frau_unter_Einflu%C3%9F","PL":"Kobieta pod presją"},"url":"kobieta_pod_presja","www":"http://en.wikipedia.org/wiki/A_Woman_Under_the_Influence","year":{"movie":1974,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48284"},"artist":"Wieslaw Rosocha","description":"Traffic Jam (Italian: L'ingorgo - Una storia impossibile) is a 1979 Italian satirical comedy-drama film directed by Luigi Comencini. It was entered into the 1979 Cannes Film Festival.","director":"Luigi Comencini","size":[67,95],"title":{"EN":"Traffic Jam","GER":"Stau","IT":"L'ingorgo - Una Storia Impossibile","PL":"Korek"},"url":"korek","www":"http://en.wikipedia.org/wiki/Traffic_Jam_(film)","year":{"movie":1978,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48296"},"artist":"Jakub Erol","description":"The Lacemaker (French: La Dentellière) is a 1977 French drama film directed by Claude Goretta and starring Isabelle Huppert and Yves Beneyton. It is based on the 1974 Prix Goncourt winning novel La Dentellière by Pascal Lainé.","director":"Claude Goretta","size":[58,84],"title":{"EN":"The Lacemaker","FR":"La Dentellière","GER":"Die Spitzenklöpplerin","PL":"Koronczarka"},"url":"koronczarka","www":"http://en.wikipedia.org/wiki/The_Lacemaker","year":{"movie":1977,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482b4"},"artist":"Romuald Socha","description":"Brief Season (Italian: Una breve stagione, also known as As Long as it Lasts) is a 1969 Italian drama film written and directed by Renato Castellani.","director":"Renato Castellani","size":[60,84],"title":{"EN":"Brief Season","GER":"-","IT":"Una Breve stagione","PL":"Krotki sezon "},"url":"krotki_sezon","www":"http://en.wikipedia.org/wiki/Brief_Season","year":{"movie":1969,"poster":1977}},
  {"_id":{"$oid":"553fb925467be23b30a482a0"},"artist":"Andrzej Pagowski","description":"One Flew Over the Cuckoo's Nest is a 1975 American drama film directed by Miloš Forman, based on the 1962 novel One Flew Over the Cuckoo's Nest by Ken Kesey, and starring Jack Nicholson, Louise Fletcher, and Will Sampson. The supporting cast features William Redfield, Brad Dourif, Danny DeVito, Christopher Lloyd, and Scatman Crothers.","director":"Miloš Forman","size":[67,95],"title":{"EN":"One Flew Over the Cuckoo's Nest","GER":"Einer flog über das Kuckucksnest","PL":"Lot nad kukułczym gniazdem"},"url":"lot_nad_kukulczym_gniazdem","www":"http://en.wikipedia.org/wiki/One_Flew_Over_the_Cuckoo%27s_Nest_(film)","year":{"movie":1975,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4828c"},"artist":"Mieczyslaw Wasilewski","description":"Macaroni (Italian: Maccheroni) is a 1985 Italian comedy film directed by Ettore Scola.[1] The film was selected as the Italian entry for the Best Foreign Language Film at the 58th Academy Awards, but was not accepted as a nominee.","director":"Ettore Scola","size":[95,67],"title":{"EN":"Macaroni","GER":"-","IT":"Maccheroni","PL":"Macaroni"},"url":"macaroni","www":"http://en.wikipedia.org/wiki/Macaroni_%28film%29","year":{"movie":1985,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4826d"},"artist":"Andrzej Nowaczyk","description":"Magic Braid filmed the novel by Feng Tszitsaya (1942). The film tells about a rustic merchant soy bad Second owning family style battle scythe, which, due to circumstances became embroiled in a conflict with the underworld Tianjin.","director":"Zien Zhang","size":[67,95],"title":{"EN":"The Magic Braid /Sen Blain","GER":"Der Zauberzopf der Shaolin","PL":"Magiczny Warkocz"},"url":"magiczny_warkocz","www":"http://www.imdb.com/title/tt0397625/combined","year":{"movie":1986,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482b3"},"artist":"Wiktor Gorka","description":"Marathon Man is a 1976 suspense/thriller film directed by John Schlesinger. It was adapted by William Goldman from his novel of the same name and stars Dustin Hoffman, Laurence Olivier, Roy Scheider, William Devane and Marthe Keller. The music score was composed by Michael Small.","director":"John Schlesinger","size":[58,84],"title":{"EN":"Marathon Man","GER":"Der Marathon-Mann","PL":"Maratończyk"},"url":"maratonczyk","www":"http://en.wikipedia.org/wiki/Marathon_Man_%28film%29","year":{"movie":1976,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482b5"},"artist":"Wieslaw Walkuski","description":"Masks (French: Masques) is a 1987 French comedy film directed by Claude Chabrol. It was entered into the 37th Berlin International Film Festival.","director":"Claude Chabrol","size":[95,67],"title":{"EN":"Masks","FR":"Masques","GER":"Masken","PL":"Lorem ipsum dolor sit amet"},"url":"maski","www":"http://en.wikipedia.org/wiki/Masks_(1987_film)","year":{"movie":1987,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48263"},"artist":"Antoni Chodorowski","description":"Mewy (Mewy /fragmenty życiorysu/) – polski dramat obyczajowy z 1986 roku w reż. Jerzego Passendorfera, na motywach powieści Stanisława Goszczurnego pod tym samym tytułem.","director":"Jerzego Passendorfera","size":[67,95],"title":{"PL":"Mewy"},"url":"mewy","www":"http://pl.wikipedia.org/wiki/Mewy_%28film%29","year":{"movie":1986,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4828d"},"artist":"Jan Mlodozeniec","description":"Swann in Love (French: Un amour de Swann, German: Eine Liebe von Swann), is a 1984 Franco-German film directed by Volker Schlöndorff. It is based on volume 1 of Marcel Proust's 1919 novel In Search of Lost Time, typically translated as Swann's Way. It was nominated for 2 BAFTA Film Awards.","director":"Volker Schlöndorff","size":[67,95],"title":{"EN":"Swann in Love","FR":"Un amour de Swann","GER":"Eine Liebe von Swann","PL":"Miłość Swanna"},"url":"milosc_swanna","www":"http://en.wikipedia.org/wiki/Swann_in_Love_(film)","year":{"movie":1984,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482b6"},"artist":"Jakub Erol","description":"Romancing the Stone is a 1984 American action-adventure romantic comedy. Directed by Robert Zemeckis, it stars Michael Douglas, Kathleen Turner and Danny DeVito. The film was followed by a 1985 sequel, The Jewel of the Nile.","director":"Robert Zemeckis","size":[67,95],"title":{"EN":"Romancing the Stone","GER":"Auf der Jagd nach dem grünen Diamanten","PL":"Miłość, szmaragd i krokodyl"},"url":"milosc_szmaragd_i_krokodyl","www":"http://en.wikipedia.org/wiki/Romancing_the_Stone","year":{"movie":1984,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48277"},"artist":"Lech Majewski","description":"Une mère et sa fille de 15 ans partent en cure pour leurs vacances. La mère tombe sous le charme d'un Italien, Giovanni, tandis que sa fille s'amourache du cuisinier de l'hôtel, Georges.","director":"Jean-Claude Brialy","size":[40.5,57.5],"title":{"EN":"-","FR":"Un Amour de pluie","GER":"Sommerliebelei","PL":"Miłość w kroplach deszczu"},"url":"milosc_w_deszczu","www":"http://fr.wikipedia.org/wiki/Un_amour_de_pluie","year":{"movie":1974,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48262"},"artist":" Jakub Ero","description":"Mona Lisa is a 1986 British neo-noir mystery drama about an ex-convict who becomes entangled in the dangerous life of a high-class call girl. The film was written by Neil Jordan and David Leland, and directed by Jordan. It was produced by HandMade Films and stars Bob Hoskins, Cathy Tyson and Michael Caine.","director":"Neil Jordan","size":[67,95],"title":{"EN":"Mona Lisa","GER":"Mona Lisa","PL":"Mona Lisa"},"url":"mona_lisa","www":"http://en.wikipedia.org/wiki/Mona_Lisa_%28film%29","year":{"movie":1986,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4828e"},"artist":"Romuald Socha","description":"That Obscure Object of Desire (French: Cet obscur objet du désir; Spanish: Ese oscuro objeto del deseo), released in 1977, was the final film directed by Luis Buñuel. Set in Spain and France against the backdrop of a terrorist insurgency, the film tells the story of an aging Frenchman who falls in love with a young Spanish woman who repeatedly frustrates his romantic and sexual desires.","director":"Luis Buñuel","size":[67,95],"title":{"EN":"That Obscure Object of Desire","ES":"Ese oscuro objeto del deseo","FR":"Cet obscur objet du désir","GER":"Dieses obskure Objekt der Begierde","PL":"Mroczny przedmiot pożądania"},"url":"mroczny_przedmiot_pozadania","www":"http://en.wikipedia.org/wiki/That_Obscure_Object_of_Desire","year":{"movie":1977,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4826e"},"artist":"Eugeniusz Skorwider","description":"The Fly is a 1986 American science fiction horror film directed and co-written by David Cronenberg. Produced by Brooksfilms and distributed by 20th Century Fox, the film stars Jeff Goldblum, Geena Davis and John Getz. It is based loosely on George Langelaan's 1957 short story of the same name, which also formed the basis for the 1958 film. The score was composed by Howard Shore and the make-up effects were created by Chris Walas, who, along with makeup artist Stephan Dupuis won the Academy Award for Best Makeup.","director":"David Cronenberg","size":[67,95],"title":{"EN":"The Fly","GER":"Die Fliege","PL":"Mucha"},"url":"mucha","www":"http://en.wikipedia.org/wiki/The_Fly_%281986_film%29","year":{"movie":1986,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4826f"},"artist":"Andrzej Pagowki","description":"On the Silver Globe (Polish: Na srebrnym globie) is a Polish film premiered in 1988, directed by Andrzej Żuławski and adapted from a novel by Jerzy Żuławski.","director":"Andrzej Żuławski","size":[67,95],"title":{"EN":"On the Silver Globe","GER":"-","PL":"Na Srebrnym Globie"},"url":"na_srebrnym_globie","www":"http://en.wikipedia.org/wiki/On_the_Silver_Globe_%28film%29","year":{"movie":1988,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48278"},"artist":"-","description":"A World Apart is a 1988 anti-Apartheid drama, written by Shawn Slovo and directed by Chris Menges. It is based on the lives of Slovo's parents, Ruth First and Joe Slovo. The film was a co-production between companies from the UK and Zimbabwe, where the movie was filmed. It features Hans Zimmer's first non-collaborative film score.","director":"Chris Menges","size":[67,95],"title":{"EN":"A World Apart","GER":"Zwei Welten","PL":"Świat na uboczu"},"url":"na_uboczu","www":"http://en.wikipedia.org/wiki/A_World_Apart_%28film%29","year":{"movie":1988,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482b7"},"artist":"Romuald Socha","description":"Buddy Buddy is a 1981 American comedy film directed by Billy Wilder that stars Jack Lemmon and Walter Matthau. The screenplay by Wilder and I.A.L. Diamond is based on the 1973 French language film L'emmerdeur, which screenwriter Francis Veber had adapted from his play Le contrat.","director":"Billy Wilder","size":[67,95],"title":{"EN":"Buddy Buddy","GER":"Buddy Buddy","PL":"Najlepszy kumpel"},"url":"najlepszy_kumpel","www":"http://en.wikipedia.org/wiki/Buddy_Buddy","year":{"movie":1981,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482a2"},"artist":"Andrzej Klimowski","description":"Cría Cuervos (English:  Ravens) is a 1976 Spanish drama film directed by Carlos Saura. The film is an allegorical drama about an eight-year-old girl dealing with loss. Highly acclaimed, it received the Special Jury Prize Award at the 1976 Cannes Film Festival.","director":"Carlos Saura","size":[67,95],"title":{"EN":"Cría Cuervos","ES":"Cría Cuervos","GER":"Züchte Raben…","PL":"Nakarmić kruki"},"url":"nakarmic_kruki","www":"http://en.wikipedia.org/wiki/Cr%C3%ADa_Cuervos","year":{"movie":1976,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482a3"},"artist":"Anna Mikke","description":"Why Shoot the Teacher? is a 1977 Canadian comedy-drama film based on a book of the same name by Max Braithwaite.","director":"Silvio Narizzano","size":[67,95],"title":{"EN":"Why Shoot the Teacher?","GER":"-","PL":"Nie strzelać do nauczyciela"},"url":"nie_strzelac_do_nauczyciela","www":"http://en.wikipedia.org/wiki/Why_Shoot_the_Teacher%3F","year":{"movie":1977,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482a4"},"artist":"-","description":"A manufacturer of furniture sees his business go down and decides to rob banks to pay his staff. Het gets romantically involved with one of his victims.","director":"Claude Goretta","size":[67,95],"title":{"EN":"The Wonderful Crook","FR":"Pas si méchant que ça","GER":"Ganz so schlimm ist er auch nicht","PL":"Nie taki zły"},"url":"nie_taki_zly","www":"http://www.imdb.com/title/tt0071974/","year":{"movie":1974,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482b8"},"artist":"Wiktor Sadowski","description":"Days of Heaven is a 1978 American drama film written and directed by Terrence Malick and starring Richard Gere, Brooke Adams, Sam Shepard and Linda Manz. Set in 1916, it tells the story of Bill and Abby, lovers who travel to the Texas Panhandle to harvest crops for a wealthy farmer. Bill encourages Abby to claim the fortune of the dying farmer by tricking him into a false marriage.","director":"Terrence Malick","size":[67,95],"title":{"EN":"Days of Heaven","GER":"In der Glut des Südens","PL":"Niebiańskie dni"},"url":"niebianskie_dni","www":"http://en.wikipedia.org/wiki/Days_of_Heaven","year":{"movie":1978,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482b9"},"artist":"-","description":"Silent Movie is a 1976 satirical comedy film co-written, directed by, and starring Mel Brooks, and released by 20th Century Fox on June 17, 1976. The ensemble cast includes Dom DeLuise, Marty Feldman, Bernadette Peters, and Sid Caesar, with appearances by Anne Bancroft, Liza Minnelli, Burt Reynolds, James Caan, Marcel Marceau and Paul Newman playing themselves.","director":"Mel Brooks","size":[58,84],"title":{"EN":"Silent Movie","GER":"Mel Brooks’ letzte Verrücktheit: Silent Movie","PL":"Nieme kino"},"url":"nieme_kino","www":"http://en.wikipedia.org/wiki/Silent_Movie","year":{"movie":1976,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482ba"},"artist":"Jerzy Flisak","description":"Trading Places is a 1983 American comedy film directed by John Landis, starring Dan Aykroyd and Eddie Murphy. It tells the story of an upper-class commodities broker and a homeless street hustler whose lives cross paths when they are unknowingly made part of an elaborate bet. Ralph Bellamy, Don Ameche, Denholm Elliott, and Jamie Lee Curtis also star. The storyline is often called a modern take on Mark Twain's classic 19th-century novel The Prince and the Pauper. It also bears a resemblance to another of Mark Twain's stories, The Million Pound Bank Note.","director":"John Landis","size":[67,95],"title":{"EN":"Trading Places","GER":"Die Glücksritter","PL":"Nieoczekiwana zmiana miejsc"},"url":"nieoczekiwana_zmiana_miejsc","www":"http://en.wikipedia.org/wiki/Trading_Places","year":{"movie":1983,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482bc"},"artist":"Andrzej Klimowski","description":"The Innocent (Italian: L'innocente) was the last film made by Italian director Luchino Visconti. Released in 1976, the film is based on the novel of the same name by Gabriele d'Annunzio.","director":"Luchino Visconti","size":[58,84],"title":{"EN":"The Innocent","GER":"Die Unschuld","IT":"L'innocente","PL":"Niewinne"},"url":"niewinne","www":"http://en.wikipedia.org/wiki/The_Innocent_(1976_film)","year":{"movie":1976,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48285"},"artist":"Jaime Carlos Nieto","description":"Los santos inocentes or The Holy Innocents is a Spanish drama film directed by Mario Camus, based on famous Miguel Delibes' novel of the same title. The movie stars Alfredo Landa and Francisco Rabal, who both won the Best Actor Award at the 1984 Cannes Film Festival.","director":"Mario Camus","size":[67,95],"title":{"EN":"The Holy Innocents","ES":"Los santos inocentes","GER":"-","PL":"Niewinni święci"},"url":"niewinni_swieci","www":"http://en.wikipedia.org/wiki/Los_santos_inocentes","year":{"movie":1984,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48270"},"artist":"Michal Piekarski","description":"Night Game is a 1989 crime drama filmed in Galveston and Houston, Texas. It stars Roy Scheider as a detective who must solve a series of murders. Released on September 15, 1989 by Epic Productions, the film was written by Spencer Eastman and directed by Peter Masterson.","director":"Peter Masterson","size":[67,95],"title":{"EN":"Night Game","GER":"-","PL":"Nocne Gry"},"url":"nocne_gry","www":"http://en.wikipedia.org/wiki/Night_Game_%28film%29","year":{"movie":1989,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482a6"},"artist":"Lech Majewski","description":"O rany, nic się nie stało!!! (EN:  Oh boy, nothing happened)- polska komedia z roku 1987 kręcona w Milanówku i Raciążu.","director":"Waldemar Szarek","size":[67,95],"title":{"EN":"-","GER":"-","PL":"O rany, nic się nie stało!!!"},"url":"o_rany_nic_sie_nie_stalo","www":"http://pl.wikipedia.org/wiki/O_rany,_nic_si%C4%99_nie_sta%C5%82o!!!","year":{"movie":1987,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482a5"},"artist":"Andrzej Piwonski","description":"El Poder del deseo nie ma jeszcze zarysu fabuły","director":"Juan Antonio Bardem","size":[67,95],"title":{"EN":"-","ES":"El Poder del deseo","GER":"-","PL":"Ofiara namiętności"},"url":"ofiara_namietnosci","www":"http://www.imdb.com/title/tt0073553/","year":{"movie":1975,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48271"},"artist":"Andrzej Piwonski","description":"Someone to Watch Over Me is a 1987 romance crime thriller film starring Tom Berenger and Mimi Rogers and directed by Ridley Scott. The film's soundtrack includes the George and Ira Gershwin song from which the film takes its title, here sung by Sting, and Vangelis' 'Memories of Green', originally from Scott's Blade Runner.","director":"Ridley Scott","size":[67,95],"title":{"EN":"Someone to Watch Over Me","GER":"Der Mann im Hintergrund","PL":"Osaczona"},"url":"osaczona","www":"http://en.wikipedia.org/wiki/Someone_to_Watch_Over_Me_(film)","year":{"movie":1987,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4826b"},"artist":"Tadeusz Trepkowski","description":"The Last Stage (Pl. Ostatni etap) was a 1947 Polish feature film directed and co-written by Wanda Jakubowska, depicting her experiences in the Auschwitz concentration camp during World War II. One feature that makes the movie very unusual is the fact that, although all actors are Poles, the ones depicting German guards speak German. This was an additional effort for the actors, but adds to the authenticity and atmosphere. The film was one of the earliest cinematic efforts to describe the Holocaust, and it is still quoted extensively by succeeding directors, including Steven Spielberg in Schindler's List.","director":"Wanda Jakubowska","size":[58,84],"title":{"EN":"The Last Stage","GER":"Die letzte Etappe","PL":"Ostatni Etap"},"url":"ostatni_etap","www":"http://en.wikipedia.org/wiki/The_Last_Stage","year":{"movie":1947,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482bd"},"artist":"Piwon, Andrzej Piwonski","description":"The Last Remake of Beau Geste is a 1977 American historical comedy film.[2] It starred and was also directed and co-written by Marty Feldman. It is a satire loosely based on the novel Beau Geste, a frequently-filmed story of brothers and their adventures in the French Foreign Legion. The humor is based heavily upon wordplay and absurdity. Feldman plays Digby Geste, the awkward and clumsy 'identical twin' brother of Michael York's Beau, the dignified, aristocratic swashbuckler.","director":"Marty Feldman","size":[60,84],"title":{"EN":"The Last Remake of Beau Geste","GER":"-","PL":"Ostatni film o Legii Cudzoziemskiej"},"url":"ostatni_film_o_legii_cudzoziemskiej","www":"http://en.wikipedia.org/wiki/The_Last_Remake_of_Beau_Geste","year":{"movie":1977,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482bb"},"artist":"Marek Freundenreich","description":"The Last Metro (French: Le Dernier Métro) is a 1980 drama film made by Les Films du Carrosse, written and directed by the French filmmaker François Truffaut, and starring Catherine Deneuve and Gérard Depardieu.","director":"François Truffaut","size":[95,67],"title":{"EN":"The Last Metro","FR":"Le Dernier Métro","GER":"-","PL":"Ostatnie Metro"},"url":"ostatnie_metro","www":"http://en.wikipedia.org/wiki/The_Last_Metro","year":{"movie":1980,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482be"},"artist":"Witold Dybowski","description":"Paris, Texas is a 1984 drama film directed by Wim Wenders and starring Harry Dean Stanton, Dean Stockwell, Nastassja Kinski, and Hunter Carson. The screenplay was written by L.M. Kit Carson and playwright Sam Shepard, and the distinctive musical score was composed by Ry Cooder. The cinematography was by Robby Müller. The film was a co-production between companies in France and West Germany, and was filmed in the United States.","director":"Wim Wenders","size":[95,67],"title":{"EN":"Paris, Texas","GER":"Paris, Texas","PL":"Paryż, Teksas"},"url":"paris_texas","www":"http://en.wikipedia.org/wiki/Paris,_Texas_%28film%29","year":{"movie":1984,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482bf"},"artist":"Wieslaw Walkuski","description":"Paris, Texas is a 1984 drama film directed by Wim Wenders and starring Harry Dean Stanton, Dean Stockwell, Nastassja Kinski, and Hunter Carson. The screenplay was written by L.M. Kit Carson and playwright Sam Shepard, and the distinctive musical score was composed by Ry Cooder. The cinematography was by Robby Müller. The film was a co-production between companies in France and West Germany, and was filmed in the United States.","director":"Wim Wenders","size":[67,95],"title":{"EN":"Paris, Texas","GER":"Paris, Texas","PL":"Paryż, Teksas"},"url":"paris_texas_2","www":"http://en.wikipedia.org/wiki/Paris,_Texas_%28film%29","year":{"movie":1984,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48286"},"artist":"Wieslaw Walkuski","description":"Pas în doi, also known as Passo Doble, is a 1985 Romanian film directed by Dan Pița. It stars Claudiu Bleonț, Petre Nicolae, Anda Onesa and Ecaterina Nazare. It was entered into the 36th Berlin International Film Festival where it won an Honourable Mention.","director":"Dan Piţa","size":[95,67],"title":{"EN":"Passo Doble","GER":"-","PL":"Paso Doble","RO":"Pas în doi"},"url":"paso_doble","www":"http://en.wikipedia.org/wiki/Pas_%C3%AEn_doi","year":{"movie":1985,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48287"},"artist":"Andrzej Pagowski","description":"Primo amore (internationally released as First Love) is a 1978 Italian comedy - drama film directed by Dino Risi. For her performance Ornella Muti won a Grolla d'oro for Best Actress.","director":"Dino Risi","size":[84,59],"title":{"EN":"First Love","GER":"Erste Liebe","IT":"Primo amore","PL":"Pierwsza Miłość"},"url":"pierwsza_milosc","www":"http://en.wikipedia.org/wiki/Primo_amore_%281978_film%29","year":{"movie":1978,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482c0"},"artist":"Marian Nowinski","description":"The Song of Roland (French: La Chanson de Roland) is a 1978 French drama film directed by Frank Cassenti and starring Klaus Kinski","director":"Frank Cassenti","size":[95,67],"title":{"EN":"The Song of Roland","FR":"La Chanson de Roland","GER":"Roland ","PL":"Pieśń o Rolandzie"},"url":"piesn_o_rolandzie","www":"http://en.wikipedia.org/wiki/The_Song_of_Roland_%28film%29","year":{"movie":1978,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48272"},"artist":"Lech Majewski","description":"Planeta Krawiec – polski film obyczajowy w reżyserii Jerzego Domaradzkiego z roku 1983. Przypowieść o prowincjonalnym krawcu, który marzył o gwiazdach. Film został oparty na autentycznej biografii Adama Giedrysa.","director":"Jerzy Domaradzki","size":[95,67],"title":{"EN":"The Planet 'tailor'","GER":"-","PL":"Planeta krawiec"},"url":"planeta_krawiec","www":"http://pl.wikipedia.org/wiki/Planeta_krawiec","year":{"movie":1983,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482c1"},"artist":"Wojciech Fangor","description":"Ashes and Diamonds (Polish: Popiół i diament) is a 1958 Polish film directed by Andrzej Wajda, based on the 1948 novel by Polish writer Jerzy Andrzejewski. It completed Wajda's war films trilogy, following A Generation (1954) and Kanal (1956). The title comes from a 19th-century poem by Cyprian Norwid and references the manner in which diamonds are formed from heat and pressure acting upon coal.","director":"Andrzej Wajda","size":[58,84],"title":{"EN":"Ashes and Diamonds","GER":"Asche und Diamant","PL":"Popiół i diament"},"url":"popiol_i_diament","www":"http://en.wikipedia.org/wiki/Ashes_and_Diamonds_(film)","year":{"movie":1958,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482c2"},"artist":"Andrzej Piwonski","description":"Dites-lui que je l'aime (English: Tell Her I Love Her) is a 1977 French film directed by Claude Miller and starring Gérard Depardieu and Miou-Miou. It is based on the 1961 novel This Sweet Sickness by Patricia Highsmith.","director":"Claude Miller","size":[84,58],"title":{"EN":"This Sweet Sickness","FR":"Dites-lui que je l'aime","GER":"Süßer Wahn","PL":"Powiedz, że ją kocham"},"url":"powiedz_ze_ja_kocham","www":"http://en.wikipedia.org/wiki/This_Sweet_Sickness_(film)","year":{"movie":1977,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48279"},"artist":"Waldemar Swierzy","description":"Blowup, or Blow-Up, is a 1966 film directed by Michelangelo Antonioni about a fashion photographer, played by David Hemmings, who believes he has unwittingly captured a murder on film. It was Antonioni's first entirely English-language film.","director":"Michelangelo Antonioni","size":[67,95],"title":{"EN":"Blowup","GER":"Blow Up","PL":"Powiększenie"},"url":"powiekszenie","www":"http://en.wikipedia.org/wiki/Blowup","year":{"movie":1966,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48264"},"artist":"Wieslaw Walkuski","description":"Po przeżyciach wojennych Stefan nie potrafi wrócić do normalnego życia. Wciąż wspomina okupację, kiedy wraz z żoną uciekł z transportu","director":"Stanisław Jędryka","size":[95,67],"title":{"PL":"Powrót na Ziemię"},"url":"powrot_na_ziemie","www":"http://pl.wikipedia.org/wiki/Powr%C3%B3t_na_ziemi%C4%99","year":{"movie":1966,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482c3"},"artist":"Maciej Kalkus","description":"Ten film nie ma jeszcze zarysu fabuły","director":"Nicolae Mărgineanu","size":[67,95],"title":{"EN":"-","GER":"-","PL":"Powrót z piekła","RO":"Intoarcerea din iad"},"url":"powrot_z_piekla","www":"http://www.filmweb.pl/film/Powr%C3%B3t+z+piek%C5%82a-1983-282686","year":{"movie":1983,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482a7"},"artist":"-","description":"Out of Africa is a 1985 American epic romantic drama film directed and produced by Sydney Pollack and starring Robert Redford and Meryl Streep. The film is based loosely on the autobiographical book Out of Africa written by Isak Dinesen (the pseudonym of Danish author Karen Blixen), which was published in 1937, with additional material from Dinesen's book Shadows on the Grass and other sources. This film received 28 film awards, including seven Academy Awards.","director":"Sydney Pollack","size":[67,95],"title":{"EN":"Out of Africa","GER":"Jenseits von Afrika","PL":"Pożegnanie z Afryką"},"url":"pozegnanie_z_afryka","www":"http://en.wikipedia.org/wiki/Out_of_Africa_(film)","year":{"movie":1985,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482a8"},"artist":"-","description":"Out of Africa is a 1985 American epic romantic drama film directed and produced by Sydney Pollack and starring Robert Redford and Meryl Streep. The film is based loosely on the autobiographical book Out of Africa written by Isak Dinesen (the pseudonym of Danish author Karen Blixen), which was published in 1937, with additional material from Dinesen's book Shadows on the Grass and other sources. This film received 28 film awards, including seven Academy Awards.","director":"Sydney Pollack","size":[84,59],"title":{"EN":"Out of Africa","GER":"Jenseits von Afrika","PL":"Pożegnanie z Afryką"},"url":"pozegnanie_z_afryka_2","www":"http://en.wikipedia.org/wiki/Out_of_Africa_(film)","year":{"movie":1985,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482c4"},"artist":"Jakub Erol","description":"Orchestra Rehearsal (Italian: Prova d'orchestra) is a 1978 Italian film directed by Federico Fellini. It follows an Italian orchestra as the members go on strike against the conductor. The film was shown out of competition at the 1979 Cannes Film Festival.","director":"Federico Fellini","size":[67,95],"title":{"EN":"Orchestra Rehearsal","GER":"Orchesterprobe","IT":"Prova d'orchestra","PL":"Próba orkiestry"},"url":"proba_orkiestry","www":"http://en.wikipedia.org/wiki/Orchestra_Rehearsal","year":{"movie":1978,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4828f"},"artist":"Wieslaw Rosocha","description":"The Incident (事件 Jiken?) is a 1978 Japanese film directed by Yoshitaro Nomura. Among many awards, it was chosen as the Best Film at the Japan Academy Prize ceremony.","director":"Yoshitarô Nomura","size":[95,67],"title":{"EN":"The Incident","GER":"-","J":"Jiken","PL":"Proces poszlakowy"},"url":"proces_poszlakowy","www":"http://en.wikipedia.org/wiki/The_Incident_%281978_film%29","year":{"movie":1978,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4827a"},"artist":"Andrzej Klimowski","description":"The Adventures of Picasso (Swedish: Picassos äventyr) is a 1978 Swedish comedy film directed by Tage Danielsson, starring Gösta Ekman, as the famous painter. The film had the tag-line Tusen kärleksfulla lögner av Hans Alfredson och Tage Danielsson (A thousand loving lies by Hans Alfredson and Tage Danielsson). At the 14th Guldbagge Awards the film won the award for Best Film.","director":"Tage Danielsson","size":[95,67],"title":{"EN":"The Adventures of Picasso","GER":"-","PL":"Przygody Picassa","SE":"Picassos äventyr"},"url":"przygody_picassa","www":"http://en.wikipedia.org/wiki/The_Adventures_of_Picasso","year":{"movie":1978,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4827d"},"artist":"Lech Majewski","description":"High Tide is a 1987 Australian film, from a script by Laura Jones, about the mother-daughter bond, directed by Gillian Armstrong. Armstrong reported that when she began work on High Tide she pinned a note above her desk: 'Blood ties. Water. Running Away.'' Jan Adele plays Lilli's mother-in-law Bet, in her film debut.","director":"Gillian Armstrong","size":[67,95],"title":{"EN":"High Tide","GER":"-","PL":"Przypływ uczuć"},"url":"przyplyw_uczuc","www":"http://en.wikipedia.org/wiki/High_Tide_(1987_film)","year":{"movie":1987,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48273"},"artist":"Anrzej Pagowski","description":"Ran (Chinese and Japanese for 'rebellion', 'uprising' or 'revolt', or to mean 'disturbed' or 'confused') is a 1985 Japanese-French jidaigeki epic film directed and co-written by Akira Kurosawa. The film stars Tatsuya Nakadai as Hidetora Ichimonji, an aging Sengoku-era warlord who decides to abdicate as ruler in favor of his three sons. The story is based on legends of the daimyo Mōri Motonari, as well as on the Shakespearean tragedy King Lear.","director":"Akira Kurosawa","size":[67,95],"title":{"EN":"Ran","GER":"-","PL":"Ran"},"url":"ran","www":"http://en.wikipedia.org/wiki/Ran_(film)","year":{"movie":1985,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48274"},"artist":"Stasys Eidrigevicius","description":"Members of an artist community opt for decadence as they anticipate the end of the world as they know it. As the storm clouds of war gather over Europe, a famous painter (Jan Nowicki) and his Bohemian friends revel in sex, drugs, and alcohol. The young artist Karol (Maciej Robakiewicz) begins his own series of paintings in between his love affairs.","director":"Andrzej Domalik","size":[67,95],"title":{"EN":"Upstairs, Downstairs","GER":"-","PL":"Schodami w górę, schodami w dół"},"url":"schodami_w_gore_schodami_w_dol","www":"http://www.nytimes.com/movies/movie/130425/Schodami-W-Gore-Schodami-W-Dol/overview","year":{"movie":1988,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48288"},"artist":"Andrzej Pagowski","description":"Seven Samurai[2] (七人の侍 Shichinin no Samurai?) is a 1954 Japanese Jidaigeki adventure film co-written, edited, and directed by Akira Kurosawa. The film takes place in 1587 during the Warring States Period of Japan. It follows the story of a village of farmers that hire seven ronin (masterless samurai) to combat bandits who will return after the harvest to steal their crops.","director":"Akira Kurosawa","size":[67,95],"title":{"EN":"Seven Samurai","GER":"Die sieben Samurai","PL":"Siedmiu samurajów"},"url":"siedmiu_samurajow","www":"http://en.wikipedia.org/wiki/Seven_Samurai","year":{"movie":1954,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48289"},"artist":"Andrzej Pagowski","description":"Siekierezada – polski film psychologiczny z 1985 roku w reżyserii Witolda Leszczyńskiego, według prozy Edwarda Stachury pt. Siekierezada albo Zima leśnych ludzi.","director":"Witold Leszczyński","size":[67,95],"title":{"EN":"-","GER":"-","PL":"Siekierezada"},"url":"siekierezada","www":"http://pl.wikipedia.org/wiki/Siekierezada_%28film%29","year":{"movie":1985,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4827b"},"artist":"Romuldt Socha","description":"The Passengers (French: Les Passagers, Italian: Viaggio di paura) is a French 1977 drama film directed by Serge Leroy and starring Jean-Louis Trintignant. It was released in the United States as The Intruder. It is based on Dean Koontz's novel Shattered.","director":"Serge Leroy","size":[95,67],"title":{"EN":"The Passengers","FR":"Les Passagers","GER":"-","PL":"Śmiertelny pościg"},"url":"smiertelny_poscig","www":"http://en.wikipedia.org/wiki/The_Passengers_%281977_film%29","year":{"movie":1977,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48290"},"artist":"Waldemar Swierzy","description":"Kagemusha (影武者 Shadow Warrior?) is a 1980 film by Akira Kurosawa. In Japanese, kagemusha is a term used to denote a political decoy. It is set in the Sengoku period of Japanese history and tells the story of a lower-class criminal who is taught to impersonate a dying warlord in order to dissuade opposing lords from attacking the newly vulnerable clan. The warlord whom the kagemusha impersonates is based on daimyo Takeda Shingen, and the film ends with the climactic 1575 Battle of Nagashino.","director":"Akira Kurosawa","size":[67,95],"title":{"EN":"Kagemusha - Shadow Warrior","GER":"Kagemusha – Der Schatten des Kriegers","J":"Kagemusha","PL":"Sobowtór"},"url":"sobowtor","www":"http://en.wikipedia.org/wiki/Kagemusha","year":{"movie":1980,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48275"},"artist":"Wiktor Sadowski","description":"Luźna adaptacja słynnej powieści Alfreda de Musseta pod tym samym tytułem. 'Spowiedź dziecięcia wieku' powstała w okresie głębokiego kryzysu duchowego i ideowego doby ponapoleońskiej szybko zyskała status jednego z najważniejszych dzieł francuskiego romantyzmu...","director":"Marek Nowicki","size":[67,95],"title":{"EN":"-","GER":"-","PL":"Spowiedź dziecięcia wieku"},"url":"spowiedz_dzieciecia_wieku","www":"http://www.filmpolski.pl/fp/index.php?film=12336","year":{"movie":1985,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48291"},"artist":"Mieczyslaw Wasilewski","description":"The Hatter's Ghost (French: 'Les Fantômes du chapelier') is a 1982 film directed by Claude Chabrol. It is based on the 1947 novel Le Petit Tailleur et le Chapelier by Georges Simenon. The film takes place in Brittany and was shot in the towns of Concarneau and Quimper.","director":"Claude Chabrol","size":[95,67],"title":{"EN":"The Hatter's Ghost","FR":"Les fantômes du chapelier","GER":"Die Fantome des Hutmachers","PL":"Sprzedawca kapeluszy"},"url":"sprzedawca_kapeluszy","www":"http://en.wikipedia.org/wiki/The_Hatter%27s_Ghost","year":{"movie":1982,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4827c"},"artist":"Lech Majewski","description":"Ten film nie ma jeszcze zarysu fabuły","director":"Liang Zang","size":[95,67],"title":{"EN":"Yamaha Fish Stall","GER":"Der Fischhändler","PL":"Yamaha, stragan rybny"},"url":"stragan_rybny","www":"http://www.filmweb.pl/film/Yamaha%2C+stragan+rybny-1984-435997","year":{"movie":1984,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482a9"},"artist":"Andrzej Pagowski","description":"Stroszek is a 1977 film by German director Werner Herzog. Written specifically for Bruno S., the film was shot in Berlin, Wisconsin, and North Carolina. Most of the lead roles are played by non-actors.","director":"Werner Herzog","size":[67,95],"title":{"EN":"Stroszek","GER":"Stroszek","PL":"Stroszek"},"url":"stroszek","www":"http://en.wikipedia.org/wiki/Stroszek","year":{"movie":1977,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48265"},"artist":"Wieslaw Walkuski","description":"Po przeżyciach wojennych Stefan nie potrafi wrócić do normalnego życia. Wciąż wspomina okupację, kiedy wraz z żoną uciekł z transportu","director":"Lenartowicz Stanislaw","size":[67,95],"title":{"EN":"Tears won't Help","PL":"Szkoda twoich łez"},"url":"szkoda_twoich_lez","www":"http://pl.wikipedia.org/wiki/Powr%C3%B3t_na_ziemi%C4%99","year":{"movie":1966,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4827e"},"artist":"-","description":"The Peanut Butter Solution (French title: Opération beurre de pinottes) is a 1985 family film. The movie was directed by Michael Rubbo and is the 2nd in the Tales for All (Contes Pour Tous) series of children's movies created by Les Productions la Fête.","director":"Michael Rubbo","size":[84,59],"title":{"EN":"The Peanut Butter Solution","FR":"Opération beurre de pinottes","GER":"Unternehmen Erdnußbutter","PL":"Tajemnica spalonego domu"},"url":"tajemnica_spalonego_domu","www":"http://en.wikipedia.org/wiki/The_Peanut_Butter_Solution","year":{"movie":1985,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482c5"},"artist":"Mieczyslaw Wasilewski","description":"3 Women is a 1977 American film written and directed by Robert Altman, and starring Shelley Duvall, Sissy Spacek and Janice Rule. It depicts the increasingly bizarre, mysterious relationship between a woman (Duvall) and her roommate and co-worker (Spacek) in a dusty, underpopulated Californian town.","director":"Robert Altman","size":[57,83],"title":{"EN":"3 Women","GER":"-","PL":"Trzy kobiety"},"url":"trzy_kobiety","www":"http://en.wikipedia.org/wiki/3_Women","year":{"movie":1977,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4826a"},"artist":"Wieslaw Walkonski","description":"Babette's Feast (Danish: Babettes gæstebud) is a 1987 Danish drama film directed by Gabriel Axel. The film's screenplay was written by Axel based on the story by Isak Dinesen (Karen Blixen). Produced by Just Betzer, Bo Christensen, and Benni Korzen with funding from the Danish Film Institute, Babette's Feast was the first Danish cinema film of a Blixen story. It was also the first Danish film to win the Academy Award for Best Foreign Language Film. The film premiered in the Un Certain Regard section of the 1987 Cannes Film Festival.","director":"Gabriel Axel","size":[84,59],"title":{"DK":"Babettes gæstebud","EN":"Babette's Feast","GER":"Babets Fest","PL":"Uczta Babette"},"url":"uczta_babette","www":"http://en.wikipedia.org/wiki/Babette's_Feast","year":{"movie":1987,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4828a"},"artist":"Romuald Socha, Elzbieta Procka","description":"Ten film nie ma jeszcze zarysu fabuły","director":"Otakar Vavra","size":[95,67],"title":{"EN":"-","GER":"-","PL":"Veronika"},"url":"veronika","www":"#","year":{"movie":1985,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4827f"},"artist":"-","description":"Un jeune couple ayant un enfant de deux ans, non conformiste, vit d'amour et de vol à l'étalage. L'un de ses deux membres finissant par être franchement excédé de cette façon de subsister, et ne prenant dès lors plus aucune précaution pour masquer ses larcins, l'histoire finira tristement. Ou comment la bohème a une fin.","director":"Jacques Rouffio","size":[67,95],"title":{"EN":"Violette \u0026 François","FR":"Violette et François","GER":"Violette und François","PL":"Violette i François"},"url":"violette_i_francois","www":"http://fr.wikipedia.org/wiki/Violette_et_Fran%C3%A7ois","year":{"movie":1977,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4825d"},"artist":"Krzysztof Nasfeter","description":"Night Moves is a 1975 mystery thriller film directed by Arthur Penn. It stars Gene Hackman, Jennifer Warren, Susan Clark, and features early career appearances by Melanie Griffith and James Woods.","director":"Arthur Penn","size":[57,40.5],"title":{"EN":"Night Moves","GER":"Die heiße Spur","PL":"W mroku nocy"},"url":"w_mroku_nocy","www":"http://en.wikipedia.org/wiki/Night_Moves_%281975_film%29","year":{"movie":1975,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4828b"},"artist":"Mieczyslaw Wasilewski","description":"Big Trouble in Little China (also known as John Carpenter's Big Trouble in Little China) is a 1986 American action film directed by John Carpenter, and starring Kurt Russell, Kim Cattrall, Dennis Dun and James Hong. The film was released in the United States on July 2, 1986. Kurt Russell plays truck driver Jack Burton, who helps his friend Wang Chi (Dennis Dun) rescue Wang's green-eyed fiancee (Suzee Pai) from bandits in San Francisco's Chinatown. They go into the mysterious underworld beneath Chinatown, where they face an ancient sorcerer named David Lo Pan (James Hong).","director":"John Carpenter","size":[84,59],"title":{"EN":"Big Trouble in Little China","GER":"-","PL":"Wielka draka w chińskiej dzielnicy"},"url":"wielka_draka_w_chinskiej_dzielnicy","www":"http://en.wikipedia.org/wiki/Big_Trouble_in_Little_China","year":{"movie":1986,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48266"},"artist":"Wiktor Sadowski","description":"Wierna rzeka (film 1983) is a Polish historical film directed by Tadeusz Chmielewski. It was produced in 1983 and released in 1987.","director":"Tadeusz Chmielewski","size":[95,67],"title":{"PL":"Wierna rzeka"},"url":"wierna_rzeky","www":"http://en.wikipedia.org/wiki/Wierna_rzeka_%281983_film%29","year":{"movie":1983,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482aa"},"artist":"Andrzej Pagowski","description":"My American Uncle (French: Mon oncle d'Amérique) is a 1980 French film directed by Alain Resnais. The film stars Gérard Depardieu, Nicole Garcia, and Roger Pierre.","director":"Alain Resnais","size":[67,95],"title":{"EN":"My American Uncle","FR":"Mon oncle d'Amérique","GER":"Mein Onkel aus Amerika","PL":"Wujaszek z Ameryki"},"url":"wujaszek_z_ameryki","www":"http://en.wikipedia.org/wiki/My_American_Uncle","year":{"movie":1980,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48293"},"artist":"Marek Ploza-Dolinski","description":"Blindfolded Eyes (Spanish: Los ojos vendados) is a 1978 Spanish drama film directed by Carlos Saura. It was entered into the 1978 Cannes Film Festival.","director":"Carlos Saura","size":[67,95],"title":{"EN":"Blindfolded Eyes","ES":"Los Ojos vendados","GER":"-","PL":"Z przewiązanymi oczami"},"url":"z_przewiazanymi_oczami","www":"http://en.wikipedia.org/wiki/Blindfolded_Eyes","year":{"movie":1978,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482ae"},"artist":"Jakub Erol","description":"Tytuł sugeruje, że film Horsta Seemanna należy do gatunku historyczno-biograficznego. Nic bardziej mylnego.","director":"Horst Seemann","size":[67,95],"title":{"EN":"-","GER":"Besuch bei Van Gogh","PL":"Z wizytą u Van Gogha"},"url":"z_wizyta_u_van_gogha","www":"http://www.filmweb.pl/film/Z+wizyt%C4%85+u+Van+Gogha-1985-35945","year":{"movie":1985,"poster":1986}},
  {"_id":{"$oid":"553fb925467be23b30a48294"},"artist":"Wieslaw Walkuski","description":"From the Life of the Marionettes (German: Aus dem Leben der Marionetten) is a 1980 film directed by Ingmar Bergman. The film was produced in West Germany with a German language screenplay and soundtrack while Bergman was in 'tax exile' from his native Sweden. It is filmed in black and white apart from two colour sequences at the beginning and end of the movie. It is set in Munich.","director":"Ingmar Bergmann","size":[95,67],"title":{"EN":"From the Life of the Marionettes","GER":"Aus dem Leben der Marionetten","PL":"Z życia marionetek"},"url":"z_zycia_marionetek","www":"http://en.wikipedia.org/wiki/From_the_Life_of_the_Marionettes","year":{"movie":1980,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a4825e"},"artist":"Jacek Kawalerowicz","description":"Murder by Death is a 1976 American mystery comedy film with a cast featuring Eileen Brennan, Truman Capote, James Coco, Peter Falk, Alec Guinness, Elsa Lanchester, David Niven, Peter Sellers, Maggie Smith, Nancy Walker, and Estelle Winwood, written by Neil Simon and directed by Robert Moore.","director":"Robert Moore","size":[58,84],"title":{"EN":"Murder by Death","GER":"Eine Leiche zum Desert","PL":"Zabity na śmierć"},"url":"zabity_na_smierc","www":"http://en.wikipedia.org/wiki/Murder_by_Death","year":{"movie":1976,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482c6"},"artist":"Janusz Kapusta","description":"The Killing of a Chinese Bookie is a 1976 American art and crime film directed and written by John Cassavetes and starring Ben Gazzara. A rough and gritty film, the formidable character Gazzara plays was based on an impersonation he did for his friend Cassavetes in the 1970s. This is the second of their three collaborations, following Husbands and preceding Opening Night.","director":"John Cassavetes","size":[58,84],"title":{"EN":"The Killing of a Chinese Bookie","GER":"Die Ermordung eines chinesischen Buchmachers","PL":"Zabójstwo chińskiego bukmachera"},"url":"zabojstwo_chinskiego_maklera","www":"http://en.wikipedia.org/wiki/The_Killing_of_a_Chinese_Bookie","year":{"movie":1976,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48295"},"artist":"Wieslaw Walkuski","description":"The Hunger is a 1983 British horror film directed by Tony Scott, and starring Catherine Deneuve, David Bowie, and Susan Sarandon. It is the story of a love triangle between a doctor who specialises in sleep and ageing research and a vampire couple. The film is a loose adaptation of the 1981 eponymous novel by Whitley Strieber, with a screenplay by Ivan Davis and Michael Thomas.","director":"Tony Scott","size":[67,95],"title":{"EN":"The Hunger","GER":"Begierde","PL":"Zagadka nieśmiertelności"},"url":"zagadka_niesmiertelnosci","www":"http://en.wikipedia.org/wiki/The_Hunger_(1983_film)","year":{"movie":1983,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a48292"},"artist":"Andrzej Klimowski","description":"Scent of a Woman is a 1992 American drama directed and produced by Martin Brest that tells the story of a preparatory school student who takes a job as an assistant to an irascible, blind, medically retired Army officer. The film stars Al Pacino, Chris O'Donnell, James Rebhorn, Philip Seymour Hoffman, and Gabrielle Anwar. It is a remake of Dino Risi's 1974 Italian film Profumo di donna.","director":"Martin Brest","size":[58,84],"title":{"EN":"Scent of a Woman","GER":"Der Duft der Frauen","PL":"Zapach kobiety"},"url":"zapach_kobiety","www":"http://en.wikipedia.org/wiki/Scent_of_a_Woman_(1992_film)","year":{"movie":1992,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482ab"},"artist":"Janusz Golik","description":"Love Till First Blood nie ma jeszcze zarysu fabuły.","director":["Dobray György","Horváth Péter"],"size":[67,95],"title":{"EN":"Love Till First Blood","GER":"Verliebt","HU":"Szerelem első vérig","PL":"Zostańmy razem"},"url":"zostanmy_razem","www":"http://www.imdb.com/title/tt0090114/synopsis?ref_=ttt_ov_pl","year":{"movie":1985,"poster":0}},
  {"_id":{"$oid":"553fb925467be23b30a482ac"},"artist":"Wasilewski Mieczyslaw","description":"Cranes Come Back To The Nest nie ma jeszcze zarysu fabuły.","director":"Chen Jialin","size":[95,67],"title":{"EN":"The Cranes Return to Nests","GER":"-","PL":"Zurawie Wracaja do gniazd"},"url":"zurawie_wracaja_do_gniazd","www":"#","year":{"movie":9999,"poster":1986}}
]};

posters.display = function() {
  "use strict";
  var landscape = 800,
      portrait = 600,
      width = landscape;

  for (var poster in posters.posters) {
    $("#poster").append(HTMLposterStart);
    // var formattedPosterTitle = HTMLposterTitle.replace("%data%", posters.posters[poster].title);
    // $(".poster-entry:last").append(formattedPosterTitle);
    // var formattedPosterDates = HTMLposterDates.replace("%data%", posters.posters[poster].dates);
    // $(".poster-entry:last").append(formattedPosterDates);
    if (posters.posters[poster].size[0] > posters.posters[poster].size[1]) {
      width = landscape;
    } else {
      width = portrait;
    };
    var formattedPosterImageURL = HTMLposterImageURL.replace("%data%", posters.posters[poster].url);
    formattedPosterImageURL = formattedPosterImageURL.replace("%width%", width);
    $(".poster-entry:last").append(formattedPosterImageURL);
    var formattedPosterCaption = HTMLposterCaption.replace("%data%", posters.posters[poster].title['PL'] + " (Poster designer: " + posters.posters[poster].artist + "; " + posters.posters[poster].size[0] + "x" + posters.posters[poster].size[1] + ")");
    $(".poster-entry:last").append(formattedPosterCaption);
    var formattedPosterDescription = HTMLposterDescription.replace("%data%", posters.posters[poster].description);
    $(".poster-entry:last").append(formattedPosterDescription);
    var formattedPosterWWW = HTMLposterWWW.replace("#", posters.posters[poster].www);
    $(".poster-entry:last").append(formattedPosterWWW);
    }
};

//strips image name from filename and adds it as alt text to all images
posters.addAltText = function() {
    "use strict";
    $(document).ready(function() {
      $('img').each(function(){
        var $img = $(this),
            filename = $img.attr('data-original') || $img.attr('src'),
            imageName = filename.substring(7, filename.lastIndexOf('.'));
        $img.attr('alt', imageName);
      });
  });
};

posters.display();
posters.addAltText();
